mixed_movies = {
    # Hollywood
    (3, 9): "Titanic",
    (9, 2): "Fast & Furious",
    (8, 5): "Marvel's Avengers",
    (7, 7): "Mr. & Mrs. Smith",
    (6, 8): "The Notebook",
    (10, 1): "John Wick",
    (5, 5): "Inception",
    (7, 6): "Deadpool",
    (9, 3): "Mad Max: Fury Road",
    (4, 9): "La La Land",
    (8, 2): "Mission Impossible",
    (7, 5): "Guardians of the Galaxy",
    (6, 7): "The Fault in Our Stars",
    (10, 2): "The Dark Knight",
    (6, 6): "Spider-Man: Homecoming",
    (5, 8): "Pride and Prejudice",
    (9, 4): "Gladiator",
    (4, 8): "The Great Gatsby",
    (8, 4): "Thor: Ragnarok",
    (6, 5): "Doctor Strange",
    (7, 4): "Iron Man",
    (3, 8): "Beauty and the Beast",
    (9, 2): "The Matrix",
    (5, 7): "Twilight",
    (7, 3): "Logan",
    (2, 10): "The Vow",
    (6, 7): "To All the Boys I've Loved Before",
    (8, 3): "Pacific Rim",
    (7, 8): "Enchanted",
    (9, 5): "Black Panther",
    (10, 2): "Extraction",
    (5, 9): "500 Days of Summer",
    (6, 4): "Sherlock Holmes",
    (8, 5): "Jurassic World",
    (7, 4): "Venom",
    (3, 10): "Me Before You",
    (9, 1): "Terminator 2",
    (6, 6): "The Hunger Games",
    (8, 3): "Batman Begins",
    (7, 7): "Pirates of the Caribbean",
    (5, 6): "Shrek 2",
    (9, 2): "Edge of Tomorrow",
    (6, 7): "Dear John",
    (7, 3): "Uncharted",
    (4, 9): "Crazy Rich Asians",
    (10, 1): "Taken",
    (8, 2): "Ready Player One",
    (6, 5): "The Amazing Spider-Man",
    (7, 6): "The Proposal",

    # Bollywood
    (7, 9): "Dilwale Dulhania Le Jayenge",
    (8, 4): "Dhoom 2",
    (6, 10): "Kabir Singh",
    (9, 2): "War",
    (5, 8): "Ae Dil Hai Mushkil",
    (10, 1): "Baahubali",
    (6, 7): "Kal Ho Naa Ho",
    (8, 3): "Singham",
    (7, 8): "Yeh Jawaani Hai Deewani",
    (5, 9): "Jab We Met",
    (9, 2): "Ghajini",
    (6, 8): "Barfi!",
    (8, 5): "Don 2",
    (7, 6): "Student of the Year",
    (10, 1): "KGF Chapter 1",
    (6, 7): "Wake Up Sid",
    (9, 3): "Bang Bang",
    (4, 9): "Veer-Zaara",
    (7, 5): "Race 2",
    (8, 6): "Chennai Express",
    (5, 8): "Kalank",
    (9, 1): "Rowdy Rathore",
    (7, 7): "Dil Chahta Hai",
    (6, 9): "2 States",
    (8, 3): "Commando",
    (7, 8): "Tamasha",
    (6, 10): "Hum Aapke Hain Koun..!",
    (8, 4): "Kesari",
    (9, 5): "Baaghi 2",
    (5, 7): "Student of the Year 2",
    (7, 8): "Bajrangi Bhaijaan",
    (8, 2): "Gully Boy",
    (6, 9): "Rehnaa Hai Terre Dil Mein",
    (7, 5): "Dishoom",
    (8, 6): "Happy New Year",
    (6, 7): "Rockstar",
    (7, 6): "Ek Tha Tiger",
    (5, 9): "Mujhse Dosti Karoge!",
    (9, 3): "Satyameva Jayate",
    (8, 5): "Bhootnath",
    (7, 4): "Force",
    (10, 2): "Sardar Udham",
    (6, 8): "Dil Dhadakne Do",
    (7, 7): "Kai Po Che!",
    (9, 2): "Singh is Kinng",
    (8, 6): "Zindagi Na Milegi Dobara",
    (7, 7): "Fanaa",
    (6, 9): "Aashiqui 2"
}

hollywood_movies = {(3, 9): "Titanic",
    (9, 2): "Fast & Furious",
    (8, 5): "Marvel's Avengers",
    (7, 7): "Mr. & Mrs. Smith",
    (6, 8): "The Notebook",
    (10, 1): "John Wick",
    (5, 5): "Inception",
    (7, 6): "Deadpool",
    (9, 3): "Mad Max: Fury Road",
    (4, 9): "La La Land",
    (8, 2): "Mission Impossible",
    (7, 5): "Guardians of the Galaxy",
    (6, 7): "The Fault in Our Stars",
    (10, 2): "The Dark Knight",
    (6, 6): "Spider-Man: Homecoming",
    (5, 8): "Pride and Prejudice",
    (9, 4): "Gladiator",
    (4, 8): "The Great Gatsby",
    (8, 4): "Thor: Ragnarok",
    (6, 5): "Doctor Strange",
    (7, 4): "Iron Man",
    (3, 8): "Beauty and the Beast",
    (9, 2): "The Matrix",
    (5, 7): "Twilight",
    (7, 3): "Logan",
    (2, 10): "The Vow",
    (6, 7): "To All the Boys I've Loved Before",
    (8, 3): "Pacific Rim",
    (7, 8): "Enchanted",
    (9, 5): "Black Panther",
    (10, 2): "Extraction",
    (5, 9): "500 Days of Summer",
    (6, 4): "Sherlock Holmes",
    (8, 5): "Jurassic World",
    (7, 4): "Venom",
    (3, 10): "Me Before You",
    (9, 1): "Terminator 2",
    (6, 6): "The Hunger Games",
    (8, 3): "Batman Begins",
    (7, 7): "Pirates of the Caribbean",
    (5, 6): "Shrek 2",
    (9, 2): "Edge of Tomorrow",
    (6, 7): "Dear John",
    (7, 3): "Uncharted",
    (4, 9): "Crazy Rich Asians",
    (10, 1): "Taken",
    (8, 2): "Ready Player One",
    (6, 5): "The Amazing Spider-Man",
    (7, 6): "The Proposal",
}

bollywood_movies = {  
    (7, 9): "Dilwale Dulhania Le Jayenge",
    (8, 4): "Dhoom 2",
    (6, 10): "Kabir Singh",
    (9, 2): "War",
    (5, 8): "Ae Dil Hai Mushkil",
    (10, 1): "Baahubali",
    (6, 7): "Kal Ho Naa Ho",
    (8, 3): "Singham",
    (7, 8): "Yeh Jawaani Hai Deewani",
    (5, 9): "Jab We Met",
    (9, 2): "Ghajini",
    (6, 8): "Barfi!",
    (8, 5): "Don 2",
    (7, 6): "Student of the Year",
    (10, 1): "KGF Chapter 1",
    (6, 7): "Wake Up Sid",
    (9, 3): "Bang Bang",
    (4, 9): "Veer-Zaara",
    (7, 5): "Race 2",
    (8, 6): "Chennai Express",
    (5, 8): "Kalank",
    (9, 1): "Rowdy Rathore",
    (7, 7): "Dil Chahta Hai",
    (6, 9): "2 States",
    (8, 3): "Commando",
    (7, 8): "Tamasha",
    (6, 10): "Hum Aapke Hain Koun..!",
    (8, 4): "Kesari",
    (9, 5): "Baaghi 2",
    (5, 7): "Student of the Year 2",
    (7, 8): "Bajrangi Bhaijaan",
    (8, 2): "Gully Boy",
    (6, 9): "Rehnaa Hai Terre Dil Mein",
    (7, 5): "Dishoom",
    (8, 6): "Happy New Year",
    (6, 7): "Rockstar",
    (7, 6): "Ek Tha Tiger",
    (5, 9): "Mujhse Dosti Karoge!",
    (9, 3): "Satyameva Jayate",
    (8, 5): "Bhootnath",
    (7, 4): "Force",
    (10, 2): "Sardar Udham",
    (6, 8): "Dil Dhadakne Do",
    (7, 7): "Kai Po Che!",
    (9, 2): "Singh is Kinng",
    (8, 6): "Zindagi Na Milegi Dobara",
    (7, 7): "Fanaa",
    (6, 9): "Aashiqui 2"
}